### ISSUE TITLE
Oil path doesnt show up in harpeek window with grapple as a picker

### ISSUE THREAD

**Issue by Sombrer0Dev** [WolfeCub/harpeek.nvim#1]
Grapple allows you to mark [Oil](https://github.com/stevearc/oil.nvim) paths
If you mark an oil path, it does not show in harpeek window

Grapple marks:
![image](https://github.com/WolfeCub/harpeek.nvim/assets/90571229/2560c9cb-eee2-493b-99f4-cbb6186948f8)

Harpeek window
![image](https://github.com/WolfeCub/harpeek.nvim/assets/90571229/6482c870-ffa3-4c7b-9110-2b06b34be4c4)

**Comment by WolfeCub** [comment]
Closed by https://github.com/WolfeCub/harpeek.nvim/commit/731013057950cd249295317ac27dcf2640075880
